# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5b3c964bd40d17b25f65ae6aeb8f0b6b8bf271dedceebe9efd837ce559ed13ec361ec973196f830c572c2b8897f6bd37dfc8374b4335dfa62414fae57afb3ad

test:
  secret_key_base: e5b50ba15fbda67b01f8a94a4f2ee8adeb70dd55658ffbaf2d3604e8b9c3de63c78e159dfad31139d28de271743a1065f93879e92a14c171e7dec9661b735a56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
